### ISSUE TITLE
I can't log into my account...

### ISSUE THREAD

**Issue by onlyFLAC** [ImAiiR/QobuzDownloaderX#158] opened 2024-10-15 04:48 UTC
I can't log into my account... None of the methods work for me, they only give an error:

ON OLD VER.:
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в QobuzDownloaderX.LoginFrm.<altLoginBG_DoWork>d__36.MoveNext()
   
ON NEW VER.:
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в QobuzDownloaderX.LoginForm.loginBackground_DoWork(Object sender, DoWorkEventArgs e)

**Comment by ImAiiR** [comment] 2024-10-15 11:53
I’m starting to think this is because of the new Qobuz updates. Is it possible for you to make a new account and try to login with that? Can just do a free trial, or maybe just don’t activate the account yet. I’d like to see if you’re able to login with a new account.

**Comment by onlyFLAC** [comment] 2024-10-15 12:15
> I’m starting to think this is because of the new Qobuz updates. Is it possible for you to make a new account and try to login with that? Can just do a free trial, or maybe just don’t activate the account yet. I’d like to see if you’re able to login with a new account.

Okay, I'll try to create a new account at home today.

**Comment by dotrungan19** [comment] 2024-10-15 15:20
same like me,I can't logging,the old version still logging successfully

**Comment by ImAiiR** [comment] 2024-10-15 16:29
> same like me,I can't login,the old version still login successfully

- Same error message? (Assuming the response isn’t returning JSON)
- Logging in with email and password or token?
- Trying with an older account or a new account?

**Comment by ImAiiR** [comment] 2024-10-16 00:00
Okay, starting to do some debugging now. From what I can see, for some reason the full passwords aren't getting sent for some reason, which is really weird. Seems to happen mainly with special characters, so hopefully won't be too difficult to fix.

**Comment by ImAiiR** [comment] 2024-10-16 04:01
Please give the new version a try and let me know if it works for you now!

**Comment by dotrungan19** [comment] 2024-10-16 09:42
> > same like me,I can't login,the old version still login successfully
> 
> * Same error message? (Assuming the response isn’t returning JSON)
> * Logging in with email and password or token?
> * Trying with an older account or a new account?


Here is the error image
https://github.com/user-attachments/assets/e370d9c1-d857-486b-98f0-097fd5558313

**Comment by dotrungan19** [comment] 2024-10-16 09:56
I've downloaded 1.0.0.1 version,when I login,it still opens this window right away,click on Continue and it works,open into app successfully
![Screenshot 2024-10-16 165401](https://github.com/user-attachments/assets/f80ce5de-0122-49a2-8471-e80a4b3e6326)

**Comment by ImAiiR** [comment] 2024-10-16 11:58
Okay, seems like now the main issue is this error that when ignored (hitting continue) the program still works as intended. Will leave this issue open for the moment until I can get the time after work to find the issues and fix it up.

**Comment by ImAiiR** [comment] 2024-10-16 23:39
For those of you who get this new error, can you confirm if the about page on the main form includes all of the info? I haven't been able to pinpoint the issue, since all of my accounts and others I know don't get this popup.

Pushing a new update here in a bit, but doubt it will resolve this specific new issue.

**Comment by vad62** [comment] 2024-10-17 06:32
The error remained at 1.0.0.2

<img width="426" alt="Снимок экрана 2024-10-17 в 09 16 00" src="https://github.com/user-attachments/assets/72081262-8fdd-42d0-8c22-f2dcd625a41c">

If you click "continue", then the application is loaded and works normally.

**Comment by iamlight33** [comment] 2024-10-18 13:53
Hi! 

For months everything was working fine in QBDLX-MOD & QBDLX, 
but now no ID / Token combinations are working for me neither in 
QBDLX 1.0.0.2 nor QBDLX-MOD 1.2.5.0, 1.2.6.0, or 1.2.7.0.

This is the error code in QBDLX-MOD 1.2.6.0 / 1.2.7.0:

Api response code: 400
Api response status: error
Api response reason: Invalid or missing app_id parameter. 

This is the error code in QBDLX-MOD 1.2.5.0:

Api response code: 401
Api response status: error
Api response reason: Invalid username/email and password combination

This is the error code in QBDLX 1.0.0.2:

System.NullReferenceException: The object reference was not set to an object instance.
   bei QobuzDownloaderX.LoginForm.loginBackground_DoWork(Object sender, DoWorkEventArgs e)

I am using the user_id / user_auth_token log in, but it's not working anymore...

Please help! Thanks in advance!

**Comment by ImAiiR** [comment] 2024-10-21 21:10
Going to say for everyone experiencing the "new" error popup, move over to #159 as it is related!
Closing this one!

**Closed by ImAiiR** 2024-10-21 21:10 UTC
