### ISSUE TITLE
Search window freeze

### ISSUE THREAD

**Issue by TheBossi** [ImAiiR/QobuzDownloaderX#114] opened 2022-03-30 15:36 UTC
- I can logon
- start the search window
- enter a term and press "search"

Issue: the whole application freezes. 

OS Windows 11 Home 10.0.22000 Build 22000

**Comment by sramsay100** [comment] 2022-03-31 00:41
This is a duplicate of #113 ,

It would appear to be a Windows 11 Issues, after a particular update.

My seacrh function on my installation loaded on Windows 10 works fine.

Workaround for now:
I never use this function myself. I always have Qobuz App or Qobuz WebPlayer loaded, find what i need, use the three dots menu, select Share and click to copy the link. Then simply paste this into QobuzDownloaderX.

Hope this helps.

**Comment by TheBossi** [comment] 2022-03-31 05:00
the workaround works fine... the search functionality is very powerful to be honest and offers a lot more options. ;-)
Thx a lot

**Comment by TheBossi** [comment] 2022-04-13 10:50
Hello everybody, I just have updated to this new WIN11 version	10.0.22000 Build 22000 and the full search is working again.

**Closed** 2024-10-14 02:49 UTC
