### ISSUE TITLE
Failed to download (First Phase). Error information below.

### ISSUE THREAD

**Issue by X-OBJECT** [ImAiiR/QobuzDownloaderX#45] opened 2020-07-20 19:05 UTC
![5656](https://user-images.githubusercontent.com/54378161/87976022-178a3600-cad5-11ea-9a4d-0d59c149ebc5.jpg)
Some albums are not dow-ded. giving it away at output of a small number shows this error.                                                           
Starting Downloads...

Failed to download (First Phase). Error information below.

System.ArgumentNullException: ....
....name of parameters: input
   в System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   в System.Text.RegularExpressions.Regex.Replace(String input, String pattern, MatchEvaluator evaluator)
   в QobuzDownloaderX.QobuzDownloaderX.DecodeEncodedNonAsciiCharacters(String value)
   в QobuzDownloaderX.QobuzDownloaderX.<downloadAlbumBG_DoWork>d__254.MoveNext()

These for example do not download:

https://play.qobuz.com/album/0782388043069 
https://play.qobuz.com/album/0603223217776 
https://play.qobuz.com/album/0782388070867

**Comment by ImAiiR** [comment] 2020-07-20 21:22
The cause is the API giving null to `copyright` (for the first and third link), and `performer` (for the second link). I hadn't seen them shown as null so didn't think this would be an issue. Thanks for giving example links, helps a ton. This should be fixed in the newest version, let me know if there are any other issues.
https://github.com/ImAiiR/QobuzDownloaderX/releases/tag/0.9.9.18

**Closed by ImAiiR** 2020-07-20 21:22 UTC
