### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by ALi3naTEd0** [ImAiiR/QobuzDownloaderX#7] opened 2020-03-23 02:14 UTC
Just downloaded the new version (first time using this app) but can't login.... here's the error log:

`System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at QobuzDownloaderX.LoginFrm.loginBG_DoWork(Object sender, DoWorkEventArgs e)`

Credentials are correct...
Thanks in advance!

**Comment by ImAiiR** [comment] 2020-03-23 02:36
So just to make sure there wasn't a double click on the MD5 button or anything, follow this.

- Close & Re-open QBDLX
- Completely clear the input boxes
- Re-enter your login info
- After typing in your password, click the MD5 button once
- Try to login again.

If that doesn't work, let me know. I can't think as to why it wouldn't be letting you log in with the correct info. Just tested on my end for my account, and all seems well.

**Comment by ALi3naTEd0** [comment] 2020-03-23 02:55
Ok still not working but I'm guessing it's a region problem since I'm not currently at the country of my account and don't have a VPN so I'm guessing it might be that...

I really appreciate the app even if it doesn't work for me so thank you very much for the help and for the work on this tool.

**Comment by ImAiiR** [comment] 2020-03-23 03:53
I'll try to do some research into the issue if I can recreate it. I don't believe it's a region issue, as my account is located in France, but I'm connected to a VPN for USA. If you manage to find a way around or anything, let me know, and I'll try to implement it for a fix.

I'll leave this issue open for others who may have the same issue, so they can keep watch or comment on it.

**Comment by ALi3naTEd0** [comment] 2020-03-24 00:25
So it looks like is not a region issue... a friend from Italy gave it a try and didn't work for him either... hope we can find the fix... Thanks!

**Comment by ImAiiR** [comment] 2020-03-24 04:10
Quick question, I don't think this could be an issue, but are there any special characters in the password (like @, !, ?, etc.)? If not, if you're trusting with your friend, could you try to find some similarities in your passwords? 

At the end of this all, it could very well be something wrong with my code on converting to MD5, only working correctly sometimes. Just not sure why it's happening.

**Comment by ALi3naTEd0** [comment] 2020-03-24 05:26
So I just checked the password and it doesn't have any special characters at all. I do trust this friend, in fact this is his account from Italy but he shared it with me in order to test it. So we both have tested it and is not working for neither of us so I'm guessing this is not a region issue nor a password one. Just to be clear, I just need to download "QBDLX_0.9.9.10.zip", extract it and run the EXE file, correct? Do you know about any other people using it without problems? Let me know if I can do something else to help, I'm more than glad. Hope we can fix this and thank you very much again.

**Comment by ImAiiR** [comment] 2020-03-24 19:07
Correct, that's all you need to do to get the program working. As long as the 2 files in the .zip are extracted to the same folder, the program should work correctly.

I've had quite a few people test this before I uploaded everything to GitHub, and it was working on their end. Did you find any similarities in the password? If not, just for testing purposes (as I don't want any real passwords you'd use), could you try changing your password to something similar to what you have now, and if it isn't working, send it my way? It'll give me something to try to work around to find the cause.

**Comment by ImAiiR** [comment] 2020-03-29 05:42
So I've decided to try and make an alternate way to log in for 0.9.9.12. If you're still having this issue, please download the latest version, and let me know if the alternate way works for you.

If you need help using this way, there's a guide on the wiki here - https://github.com/ImAiiR/QobuzDownloaderX/wiki/Logging-In-(The-Alternate-Way)

I won't close this until I know it works for you, as I'm the only one who has tested this.

**Comment by mitch-empiri** [comment] 2020-03-29 14:23
Hi!
My QobuzDownloaderX does not want to work.I go into the program via login and password,but does not want to download the release.What could be the problem?
https://i.imgur.com/b4bJoDT.jpg

Same thing with Qo-DL Reborn,stopped working yesterday :(
https://i.imgur.com/2ps4NG9.jpg

Please, help to understand what is the matter.

**Comment by ImAiiR** [comment] 2020-03-29 20:06
> Hi!
> My QobuzDownloaderX does not want to work.I go into the program via login and password,but does not want to download the release.What could be the problem?
> https://i.imgur.com/b4bJoDT.jpg
> 
> Same thing with Qo-DL Reborn,stopped working yesterday :(
> https://i.imgur.com/2ps4NG9.jpg
> 
> Please, help to understand what is the matter.

Please open another issue. Your issue isn't related to not being able to log in.

**Comment by ALi3naTEd0** [comment] 2020-04-01 01:22
I finally logged in with the new alternative way! Using email + password still not working but thanks for the fix.

**Closed** 2020-04-01 07:59 UTC
Labels: bug

**Comment by neilwilkes** [comment] 2022-06-06 10:52
I am having the same issue - unable to log in (UK account)
Also tried the alternative method, but that also is not working & I cannot understand why

**Comment by neilwilkes** [comment] 2022-06-06 11:05
Update.
This is with Google Chrome browser on both Windows 7 & Windows 10.
It recently just suddenly stopped working and since then it has never worked at all.

**Comment by tucatucz** [comment] 2022-07-01 06:13
Same issue here. Even with the alternative method i can't login.

**Comment by neilwilkes** [comment] 2022-07-01 09:50
There is a 'fixed/recompiled' version in a thread here somewhere - that works.

**Comment by joemar444** [comment] 2023-01-07 05:28
> There is a 'fixed/recompiled' version in a thread here somewhere - that works.

cant find it

**Comment by user147852** [comment] 2023-01-14 15:48
Hi!
A similar problem for a UK account. No login method helps.
